import {IconDefinition} from "@fortawesome/free-regular-svg-icons";
import {
  faArrowUp,
  faBookReader,
  faBriefcase,
  faBullhorn,
  faChartLine,
  faClipboardCheck,
  faClipboardList,
  faDonate,
  faFileAlt,
  faFire,
  faHandHoldingHeart,
  faHandshake,
  faHeart,
  faLightbulb,
  faNewspaper,
  faPeopleCarry,
  faRss,
  faStar,
  faTasks,
  faUser,
  faUserAlt,
  faUserCircle,
  faUserTie,
  faBars,
  faSignInAlt,
  faKey,
  faSignOutAlt,
  faRightFromBracket,
  faUnlockKeyhole, faLock
} from "@fortawesome/free-solid-svg-icons";

export const fontAwesomeIcons: IconDefinition []= [
  faUser, faUserAlt, faUserCircle,
  faHandshake,faBriefcase,faUserTie,
  faTasks, faClipboardCheck, faPeopleCarry,
  faBullhorn,faClipboardList, faFileAlt,
  faNewspaper, faBullhorn,faRss,
  faChartLine,faFire, faArrowUp,
  faClipboardCheck, faLightbulb, faBookReader,
  faHandHoldingHeart,
  faDonate, faHeart,
  faStar,
  faBars,
  faSignInAlt,
  faKey,
  faSignOutAlt,
  faRightFromBracket,
  faUnlockKeyhole,
  faLock
]
