logging:
  level:
    org:
      springframework:
        security: DEBUG
    com:
      mycompany: INFO

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hybrid_api
    username: postgres
    password: draslom3
    driverClassName: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false

  flyway:
    enabled: true
    baseline-on-migrate: true

  security: #dev-lbu4c820m2nza8vh.us.auth0.com
    oauth2:
      client:
        registration:
          auth0:
            client-id: ${AUTH0_CLIENT_ID}
            client-secret: ${AUTH0_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/auth0"
            provider: auth0
        provider:
          auth0:
              issuer-uri: https://dev-lbu4c820m2nza8vh.us.auth0.com/
              authorization-uri: https://dev-lbu4c820m2nza8vh.us.auth0.com/authorize
              token-uri: https://dev-lbu4c820m2nza8vh.us.auth0.com/oauth/token
              user-info-uri: https://dev-lbu4c820m2nza8vh.us.auth0.com/userinfo
              jwk-set-uri: https://dev-lbu4c820m2nza8vh.us.auth0.com/.well-known/jwks.json
              user-name-attribute: sub
auth0:
  oauth2:
    issuer: https://dev-lbu4c820m2nza8vh.us.auth0.com/
    client-id: ${AUTH0_CLIENT_ID}
    client-secret: ${AUTH0_CLIENT_SECRET}
    redirect-uri: "{baseUrl}/login/oauth2/code/auth0"
  #rol_bMjiQLmAN3LUSbqi
application:
  auth0:
    role-landlord-id: rol_cCOaub7vwRyW2Brg

