debug: true # Ajoutez cette ligne ici
logging:
  level:
    org:
      springframework:
        security: TRACE #DEBUG
    com:
      mycompany: INFO

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hybrid_api
    username: postgres
    password: draslom3
    driverClassName: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    show-sql: false

  flyway:
    enabled: true
    baseline-on-migrate: true

#      resourceserver:
#        jwt:
#          issuer-uri: https://dev-lbu4c820m2nza8vh.us.auth0.com/
##          audiences:
##            - https://alhas.com/api
#
jwt:
  secret: "WoslKZzExlBMQ5IdfaG2Gye5bIyEI0X17X0+6hyDAf7rWk2BvBbp9RPBrNZronFU/7Lxbk2CdNalrWm55Dk4Rw=="

# application.yml
management:
  endpoints:
    web:
      exposure:
        include: "*"




server:
  port: 8081